name: Release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build action
        run: npm run build

      - name: Check for release labels
        id: check-labels
        run: |
          labels="${{ toJson(github.event.pull_request.labels.*.name) }}"
          echo "Labels: $labels"
          
          if echo "$labels" | grep -q "major\|minor\|patch"; then
            echo "has-release-label=true" >> $GITHUB_OUTPUT
          else
            echo "has-release-label=false" >> $GITHUB_OUTPUT
          fi

      - name: Test action
        if: steps.check-labels.outputs.has-release-label == 'true'
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: No release
        if: steps.check-labels.outputs.has-release-label == 'false'
        run: |
          echo "ℹ️ No release labels found. Add 'major', 'minor', or 'patch' labels to create a release."
